### ISSUE TITLE
[BUG] Android: Fix crash in exposures - removeExpiredTime

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/safer-illinois-app#629]
**Describe the bug**
Fix crash in Android reported in firebase console. Stacktrace:

`
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
       at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
       at edu.illinois.covid.exposure.ExposurePlugin.removeExpiredTime(ExposurePlugin.java:31)
       at edu.illinois.covid.exposure.ExposurePlugin.saveExpUpTimeToStorage(ExposurePlugin.java)
       at edu.illinois.covid.exposure.ExposurePlugin.stopExpUpTimeTimer(ExposurePlugin.java:47)
       at edu.illinois.covid.exposure.ExposurePlugin.startExpUpTimeTimer(ExposurePlugin.java:9)
       at edu.illinois.covid.exposure.ExposurePlugin.start(ExposurePlugin.java:16)
       at edu.illinois.covid.exposure.ExposurePlugin.g(ExposurePlugin.java:8)
       at edu.illinois.covid.exposure.ExposurePlugin.access$300(ExposurePlugin.java)
       at edu.illinois.covid.exposure.ExposurePlugin$3.onServiceConnected(ExposurePlugin.java:58)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1739)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1771)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:215)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
`

**To Reproduce**
There are no clear steps for reproducing

**Expected behavior**
No crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android

**Smartphone (please complete the following information):**

**Comment by dobromirdobrev** [comment]
Fixed in 2.10.23 and above.
