### ISSUE TITLE
[BUG] Android: Fix crash in exposures - processExposures

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/safer-illinois-app#631]
**Describe the bug**
Fix crash in Android reported in firebase console. Stacktrace:
`
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
       at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
       at edu.illinois.covid.exposure.ExposurePlugin.processExposures(ExposurePlugin.java:39)
       at edu.illinois.covid.exposure.ExposurePlugin.access$1800(ExposurePlugin.java)
       at edu.illinois.covid.exposure.ExposurePlugin$9.run(ExposurePlugin.java:2)
       at java.util.TimerThread.mainLoop(TimerThread.java:555)
       at java.util.TimerThread.run(TimerThread.java:505)
`

**To Reproduce**
There are no clear steps for reproducing

**Expected behavior**
No crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android

**Smartphone (please complete the following information):**

**Comment by dobromirdobrev** [comment]
Fixed in 2.10.23 and above
