### ISSUE TITLE
[BUG] Android crash in exposures - NPE

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/safer-illinois-app#68]
From Crashlytics:

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {edu.illinois.covid/edu.illinois.covid.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeScanner.stopScan(android.app.PendingIntent)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5351)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5385)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8034)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by dobromirdobrev** [comment]
Fixed in both 2.4 & 2.5
