### ISSUE TITLE
[BUG] Android: Fix ConcurrentModificationException when processing exposures

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/safer-illinois-app#688]
**Describe the bug**
Fix crash in Android reported in firebase console. Stacktrace:
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
       at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
       at edu.illinois.covid.exposure.ExposurePlugin.processExposures(ExposurePlugin.java:39)
       at edu.illinois.covid.exposure.ExposurePlugin.access$1800(ExposurePlugin.java)
       at edu.illinois.covid.exposure.ExposurePlugin$9.run(ExposurePlugin.java:2)
       at java.util.TimerThread.mainLoop(TimerThread.java:562)
       at java.util.TimerThread.run(TimerThread.java:512)
```

**To Reproduce**
There are no steps for reproducing.

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: Android devices
 - OS: Android 8.0 and above

**Comment by dobromirdobrev** [comment]
Fixed in version 2.10.35
