### ISSUE TITLE
[BUG] Android: Fix crash - RemoteServiceException

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/safer-illinois-app#690]
**Describe the bug**
Fix crash in Android reported in firebase console. Stacktrace:
```
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{74b296 u0 edu.illinois.covid/.exposure.ble.ExposureClient}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2190)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**To Reproduce**
There are no steps to reproduce.

**Expected behavior**
No crash.

**Smartphone (please complete the following information):**
 - Device: Android devices
 - OS: Android 8.0 and above

**Comment by dobromirdobrev** [comment]
Fixed in version 2.10.35.
