### ISSUE TITLE
[BUG] Android crash in exposures - BT adapter is not turned on

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/safer-illinois-app#70]
From Crashlytics:

```
Fatal Exception: java.lang.IllegalStateException: BT Adapter is not turned ON
       at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:177)
       at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:278)
       at edu.illinois.covid.d.f.B(:15)
       at edu.illinois.covid.d.f.c(:7)
       at edu.illinois.covid.d.a.run(:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by dobromirdobrev** [comment]
Fixed.
