### ISSUE TITLE
[BUG] Android crash in exposures - failed to start service

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/safer-illinois-app#74]
From Crashlytics:

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver edu.illinois.covid.exposure.ble.scan.ExposureBleReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=edu.illinois.covid/.exposure.ble.ExposureClient (has extras) }: app is in background uid UidRecord{a726422 u0a46 RCVR idle change:uncached procs:1 proclist:3537, seq(0,0,0)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3614)
       at android.app.ActivityThread.access$1300(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1798)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by dobromirdobrev** [comment]
Fixed
